### ISSUE TITLE
no route due to ScidAliasOptional

### ISSUE THREAD

**Issue by phr34k** [ACINQ/phoenix#317]
I always get an `no_route` error trying to send money to a phoenix wallet (off-chain) from my lnd node because of feature bit 47 is `ScidAliasOptional`.  See https://github.com/lightningnetwork/lnd/issues/7191 for full problem description.

**Comment by t-bast** [comment]
That means your Phoenix application isn't up-to-date, this has been fixed in the latest version.

**Comment by phr34k** [comment]
@t-bast I do have the latest installed but to avoid argument I went ahead and dowloaded the latest apk (testnet) in the faq section and updated the phoenix application on my phone, the problem persists.  The testnet version does state (in-app) there's an update available, I assumed it was false-positive due to not being the regular version distributed through the playstore. is it possible that that the apk of the testnet version isn't up-to-date and in fact an older version?

**Comment by t-bast** [comment]
You didn't mention that you were on testnet. This is fixed on mainnet and on the github repository, but it looks like the link for the testnet apk doesn't link to the latest version.

The latest version that fixes this issue is at this commit: https://github.com/ACINQ/phoenix/releases/tag/android-legacy-v1.4.23 
But the github link to the testnet apk installs the previous version.
@dpad85 do you know how to update the latest testnet apk?

But if you use Phoenix mainnet, this issue has been fixed for a couple of months.

**Comment by phr34k** [comment]
Fair enough, I mentioned testnet on the origional ticket @lnd who flagged it as interopabillity issue on phoenix/eclair side. If I can get my hands on a testnet version of the latest apk I'll give it a try, Any chance you can update https://acinq.co/pub/phoenix/phoenix-testnet-latest.apk to the lastest version?

**Comment by dpad85** [comment]
Sorry about that, the testnet APK is indeed not updated anymore automatically. It must be done manually. I've updated the file, if you install it payments from lnd should now work.

The android phoenix app is in a transition and there are many moving parts. Once the migration is done, we will be able to fix the testnet build. In the meantime things may break. Thanks for reporting this!
